version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: qreserve
      POSTGRES_USER: qreserve
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U qreserve"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://qreserve:password@postgres:5432/qreserve
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app/backend
      - ./uploads:/app/uploads
    command: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000 --reload

  celery:
    build: .
    environment:
      - DATABASE_URL=postgresql://qreserve:password@postgres:5432/qreserve
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app/backend
      - ./uploads:/app/uploads
    command: celery -A backend.app.core.celery worker --loglevel=info

volumes:
  postgres_data:
  redis_data: 